### ISSUE TITLE
Segmentation fault in VO-SF-ImageSeq

### ISSUE THREAD

**Issue by naiveHobo** [MarianoJT88/Joint-VO-SF#1]
The GitHub repository does not contain the 'joint_vo_sf.cpp' file which contains basically all the code needed to run this visual odometry code.

**Comment by MarianoJT88** [comment]
I think it is not missing (nor required by CMake when configuring/generating the project). The code is distributed in different .cpp files; solver.cpp is probably the core of it.

Is your compiler or CMake complaining about that?

**Comment by naiveHobo** [comment]
I'm sorry, I didn't have a look at the other files. Anyway, I'm getting a segmentation fault when I try to run VO-SF-ImageSeq with my own dataset.

**Comment by MarianoJT88** [comment]
Check resolution and the dir name you have set to read the sequence
