### ISSUE TITLE
Some questions about showing the sceneflow results

### ISSUE THREAD

**Issue by progressforever** [MarianoJT88/Joint-VO-SF#15]
Thanks for your excellect work firstly.
I want to show my own sceneflow reslult with your visualization tools. However, it shows different from real sceneflow result.
The range of my sceneflow values and depth values are both normal.  But the length of sceneflow is abnormal.
After my double check, i find that when i scale my depth value, it performs well.
I guess the `depth.convertTo(depth_float, CV_32FC1, 1.0 / 500.0)` is important for me. My depth map is obtained by sgbm and with unit of mm. 
Looking for your early reply, thank you again for your excellent work.

**Comment by MarianoJT88** [comment]
Hi, thanks.
I haven´t touched this code in long time but yes, I think depth should be expressed in meters. Anyway it sounds like you found a solution for it already.

**Comment by progressforever** [comment]
> Hi, thanks.
> I haven´t touched this code in long time but yes, I think depth should be expressed in meters. Anyway it sounds like you found a solution for it already.

Thanks for your detailed reply~
