### ISSUE TITLE
Use the image pyramid is to K-means ?

### ISSUE THREAD

**Issue by payne11** [MarianoJT88/Joint-VO-SF#7]
After reading your paper, I still do not know your whole algorithm. I just know that your algorithm is roughly divided into three parts. The first part of the K-means clustering objects and the second part of the M-estimator to calculate the photometric and geometric residuals, and then dynamic object segmentation, the third part has a feedback parameter B for the next segmentation , could you simply introduce what algorithm is used,thank you !

**Comment by MarianoJT88** [comment]
Hi, the algorithm is composed of more blocks, not only those three. You can check the order in the first figure of the paper but we have basically:
- K-Means clustering using the 3D coordinates of the points.
- Robust odometry (not to calculate the residuals but to calculate the camera motion).
- Static/dynamic segmentation of the scene done per cluster.
- Scene flow estimation for moving clusters.
- Odometry refinement with the static clusters.
- Segmentation refinement.

If this doesn't answer your question please specify what you want to know exactly.

**Comment by payne11** [comment]
i do not know about Robust odometry. Could you give me some references, and I hope that i will have  a further understanding of Robust odometry,Thank you !

**Comment by MarianoJT88** [comment]
You can read the section about motion estimation of this paper:
Motion Cooperation: Smooth Piece-Wise Rigid Scene Flow from RGB-D Images, 3DV 2015

You can also read this one. It focuses on odometry and might be a better option to start:
Robust odometry estimation for rgb-d cameras, ICRA 2013

**Comment by payne11** [comment]
Thank you for your patience！I  read BACKGROUND SEGMENTATION again, I found that i can't understand this part, Could you recommend some relevant information? Thank you !

**Comment by MarianoJT88** [comment]
No sorry for that all you have is this paper, I don't know very similar approaches that could help you understand it.

**Comment by payne11** [comment]
Thank you for your timely reply, I am sorry to trouble you again, the code part of a place I do not understand, I hope you can answer my doubts,`kmeans(0,l) = depth_sorted[l].at(med_pos);kmeans(1,l) = (u_label[l]-disp_u_i)*kmeans(0,l)*inv_f_i;kmeans(2,l) = (v_label[l]-disp_v_i)*kmeans(0,l)*inv_f_i;`i don't know that the meaning of the three paragraphs code, i  just know that`u_label[l]`and`v_label[l]` is the cluster point at the beginning ,and `depth_sorted[l].at(med_pos)` is that the middle depth of the value belong to i cluster ,could you tell me the meaning of these three paragraphs generally?
