### ISSUE TITLE
In each layer of the image pyramid using K-means ?

### ISSUE THREAD

**Issue by payne11** [MarianoJT88/Joint-VO-SF#8]

**Comment by payne11** [comment]
Besides , i feel  not match in this part of the program and the paper.
`trunc_res = max(0.007f, min(0.015f*(1.f + 10.f*twist_odometry.norm()), median_res));`
`lim_nobackg = (1.f + 10.f*twist_odometry.norm())*trunc_res;`
`lim_backg = (2.f + 10.f*twist_odometry.norm())*trunc_res`
according to your program that it  should write as follows:
δ̂ t = max(t M , min(t B , δ̂)) ,
δ L = δ̂ t(1+ 10 kξ R k 2) ,δ H = δ̂ t (2 + 10 kξ R k 2) .
rather than  written in your paper as follows:
δ̂ t = min(t M , max(t B , δ̂)) ,
δ L = δ̂ t + 10 kξ R k 2 ,δ H = 2 δ̂ t + 10 kξ R k 2 .
 Maybe I have not understood yet, can you explain it to me? Thank you!

**Comment by MarianoJT88** [comment]
Those thresholds / limits are very heuristic and there might be small differences between the equation presented in the paper and my last implementation on the code. I would keep the limits as they are on the code but you can change and play with those if you want, maybe you get something even better than that.
